name: gakunote
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.1.0
  uuid: ^4.0.0
  flutter_markdown: ^0.6.0
  intl: ^0.19.0
  flutter_math_fork: ^0.7.3
  
  # 状態管理
  provider: ^6.1.2
  
  # ローカルストレージ
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  injectable: ^2.5.0
  
  # Firebase (オプション)
  firebase_core: ^2.5.0
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5

  shared_preferences: ^2.0.0

  pdf: ^3.10.4
  flutter_image_compress: ^2.0.0
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  # アセット
  # assets:
  #   - assets/images/
  
  # フォント
  # fonts:
  #   - family: NotoSansJP
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.otf
  #       - asset: assets/fonts/NotoSansJP-Bold.otf
  #         weight: 700