// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5yxnk7m9bS2xmu1E5fJTERlr2T51VB7A',
    appId: '1:352580638198:web:c01b13dd7b4fdd2fd9a3d7',
    messagingSenderId: '352580638198',
    projectId: 'gakunote-fcb98',
    authDomain: 'gakunote-fcb98.firebaseapp.com',
    storageBucket: 'gakunote-fcb98.firebasestorage.app',
    measurementId: 'G-BR0D9W85LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR9TqB06o_rPgQh0N8MV-THM5qLMjL5gs',
    appId: '1:352580638198:android:297c9597b4114eccd9a3d7',
    messagingSenderId: '352580638198',
    projectId: 'gakunote-fcb98',
    storageBucket: 'gakunote-fcb98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-0wi_bIpnAKqofSkUlVo8bw97YXyNK4k',
    appId: '1:352580638198:ios:bdb499f6ac22e830d9a3d7',
    messagingSenderId: '352580638198',
    projectId: 'gakunote-fcb98',
    storageBucket: 'gakunote-fcb98.firebasestorage.app',
    iosBundleId: 'com.example.gakunote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-0wi_bIpnAKqofSkUlVo8bw97YXyNK4k',
    appId: '1:352580638198:ios:bdb499f6ac22e830d9a3d7',
    messagingSenderId: '352580638198',
    projectId: 'gakunote-fcb98',
    storageBucket: 'gakunote-fcb98.firebasestorage.app',
    iosBundleId: 'com.example.gakunote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5yxnk7m9bS2xmu1E5fJTERlr2T51VB7A',
    appId: '1:352580638198:web:3882c5337fcdeb24d9a3d7',
    messagingSenderId: '352580638198',
    projectId: 'gakunote-fcb98',
    authDomain: 'gakunote-fcb98.firebaseapp.com',
    storageBucket: 'gakunote-fcb98.firebasestorage.app',
    measurementId: 'G-GC8CFTT6EH',
  );

}